sudo: enabled
dist: trusty
language: python
python:
  - 3.6

before_install:
  - sudo apt-get -yq install software-properties-common
  - sudo apt-add-repository -y multiverse
  - sudo apt-get -yq update
  - sudo apt-get -yq install automake build-essential libyaml-dev
  - pip install -r requirements.txt
  - pip install coveralls pyre-check
  - mkdir plugins

install:
  - python3 setup.py install

script:
  - pyre check --noninteractive
  - coverage run setup.py test

after_success: coveralls
